import { Layout, ScrollTop } from "@components"
import { AuthProvider } from "contexts/AuthContext"
import "@styles/globals.css"
import type { AppProps } from "next/app"
import Head from "next/head"

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<AuthProvider>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Layout>
				<Component {...pageProps} />
			</Layout>

			<ScrollTop />
		</AuthProvider>
	)
}

export default MyApp
