import type { NextPage } from "next";
import Head from "next/head";
import { Fragment, useEffect } from "react";

import style from "@styles/home.module.scss";
import { trpc } from "hooks/trpc";

const Home: NextPage = () => {
	console.count("render");

	useEffect(() => {
		const run = async () => {
			const test = await trpc.test.query();
			console.log(test); // <- Works
		};
		run();
	}, []);

	return (
		<Fragment>
			<Head>
				<title>Its home here</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<h1 className={style.title}>Testing !!</h1>
		</Fragment>
	);
};

export default Home;
