import type { NextPage } from "next";
import Head from "next/head";
import { Fragment, useEffect } from "react";
import { trpc } from "@libs/trpc";

const Home: NextPage = () => {
	useEffect(() => {
		const run = async () => {
			// const test = await trpc...
		};
		run();
	}, []);

	return (
		<Fragment>
			<Head>
				<title>Its home here</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<h1 className="">Testing !!</h1>
		</Fragment>
	);
};

export default Home;
