import "@styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Fragment } from "react";

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			{/* HEADER */}

			<main>
				<Component {...pageProps} />
			</main>

			{/* FOOTER */}
		</Fragment>
	);
}

export default MyApp;
