import type { NextPage } from "next";
import Head from "next/head";
import { Fragment } from "react";

import style from "@styles/home.module.scss";

const Home: NextPage = () => {
	return (
		<Fragment>
			<Head>
				<title>Its home here</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<h1 className={style.title}>Testing !!</h1>
		</Fragment>
	);
};

export default Home;
